# Generated by Django 3.2.19 on 2024-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('posted_by', models.CharField(max_length=50)),
                ('extract', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
