# Generated by Django 3.2.19 on 2024-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_auto_20240228_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='images'),
        ),
    ]
