# Generated by Django 3.2.19 on 2024-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0011_auto_20240302_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagesecond',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagethird',
            field=models.ImageField(upload_to='images'),
        ),
    ]
